name: "Enforce Readme"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a readme file on every pull request
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: 'README.md'
        skipLabels: 'skip readme'
        missingUpdateErrorMessage: >
            No update to README.md found! Please add a README
            update if you have updated a version in GFE.
            If your change is very trivial not applicable for a
            README entry, add a 'skip readme' label to the pull
            request to skip the README enforcer.

