name: Windows CI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Do not run if the only files changed cannot affect the build
    paths-ignore:
      - "**.md"
      - "**.MD"
      - "LICENCE"
      - "COPYRIGHT"
  # Allow the scheduled workflow to reuse this test matrix if needed.
  workflow_call:
  # Allow us to trigger it manually
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Windows-GNU:
    name: Windows / gfortran
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true

      - name: Set all directories as git safe
        run: |
          git config --global --add safe.directory '*'

      - name: Install m4
        run: choco install gnuwin32-m4 -y

      - name: Set up Fortran (MinGW gfortran)
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc

      - name: Versions
        run: |
          gfortran --version
          gcc --version
          ninja --version
          cmake --version

      - name: Build and Install GFE
        run: |
          cmake -B build -G "Ninja" \
            -DCMAKE_Fortran_COMPILER=gfortran \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_Fortran_FLAGS="-D_WIN32" \
            -DSKIP_MPI=YES \
            -DSKIP_OPENMP=ON \
            -DSKIP_ROBUST=YES \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install" \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/install"
          cmake --build build --parallel 4 --target install
          cmake -B build -G "Ninja" \
            -DCMAKE_Fortran_COMPILER=gfortran \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_Fortran_FLAGS="-D_WIN32" \
            -DSKIP_MPI=YES \
            -DSKIP_OPENMP=ON \
            -DSKIP_ROBUST=YES \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install" \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/install"
          cmake --build build --parallel 4 --target install

      - name: Build and Run Tests target
        run: |
          cmake --build build --parallel 4 --target build-tests
          rm -f build/CTestCustom.cmake
          cmake --build build --parallel 4 --target tests || ctest --test-dir build --parallel 4 --output-on-failure --repeat until-pass:4

      - name: Run Ctest
        run: |
          rm -f build/CTestCustom.cmake
          ctest --test-dir build --parallel 4 --output-on-failure --repeat until-pass:4

      - name: Archive log files on failure
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: logfiles-Windows-GNU
          path: |
            build/**/*.log

  Windows-Intel:
    name: Windows / ifx
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true

      - name: Set all directories as git safe
        run: |
          git config --global --add safe.directory '*'

      - name: Install m4
        run: choco install gnuwin32-m4 -y

      - name: Set up Intel Fortran (ifx)
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: intel
          version: "2025.3.2"

      - name: Set up MSVC toolchain
        uses: ilammy/msvc-dev-cmd@v1

      - name: Versions
        run: |
          ifx --version
          cl
          ninja --version
          cmake --version

      - name: Build and Install GFE
        run: |
          cmake -B build -G "Ninja" \
            -DCMAKE_Fortran_COMPILER=ifx \
            -DCMAKE_C_COMPILER=cl \
            -DSKIP_MPI=YES \
            -DSKIP_OPENMP=ON \
            -DSKIP_ROBUST=YES \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install" \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/install"
          cmake --build build --parallel 4 --target install
          cmake -B build -G "Ninja" \
            -DCMAKE_Fortran_COMPILER=ifx \
            -DCMAKE_C_COMPILER=cl \
            -DSKIP_MPI=YES \
            -DSKIP_OPENMP=ON \
            -DSKIP_ROBUST=YES \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install" \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/install"
          cmake --build build --parallel 4 --target install

      - name: Build and Run Tests target
        run: |
          cmake --build build --parallel 4 --target build-tests
          rm -f build/CTestCustom.cmake
          cmake --build build --parallel 4 --target tests || ctest --test-dir build --parallel 4 --output-on-failure --repeat until-pass:4

      - name: Run Ctest
        run: |
          rm -f build/CTestCustom.cmake
          ctest --test-dir build --parallel 4 --output-on-failure --repeat until-pass:4

      - name: Archive log files on failure
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: logfiles-Windows-Intel
          path: |
            build/**/*.log
